### ISSUE TITLE
TAC lookup issue

### ISSUE THREAD

**Issue by kirsring** [51Degrees/cloud-issues#15] opened 2023-03-27 14:51 UTC
A cloud release last week has resulted in an issue regarding the TAC lookup not detecting correctly. An update to the cloud will be performed this week which hopefully should resolve this issue.

Any further update will be tracked here. Any questions, please comment on this GitHub issue.

**Comment by ghost** [comment] 2023-03-28 09:06
We have prepared a fix which should be going live soon! Once complete I will confirm the issue is resolved and close this issue.

**Comment by ghost** [comment] 2023-03-29 08:41
A cloud update was released Tuesday evening which resolved the TAC lookup issue. I will now close this issue, but please let us know if you spot anything unusual!

**Closed as completed** 2023-03-29 09:05 UTC
